//
// file:			main_any_quick_test.c
// path:			src/tests/main_any_quick_test.c
// created on:		2023 May 08
// created by:		Davit Kalantaryan (davit.kalantaryan@gmail.com)
//


#include <simple_cpp_bcrypt/bcrypt.h>
#include <stdio.h>
#include <assert.h>


struct SPassAndHash {
	const char* password;
	const char* hash;
};


// some correct passwords (generated by https://pi7.org/bcrypt-online/)
static const struct SPassAndHash  s_correctPairs[] = {
	{"Password1","$2a$12$kCqMi6/ICcWoNdpqT4Ly7ul5EwEUzZVRZsT0cxUq.cKQGcpGDJ.M."},
	{"Password2","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uj7QNDFFHtJyQNyh.DvBYB9mCrlPDJ/u"},
	{"Password3","$2a$12$kCqMi6/ICcWoNdpqT4Ly7ui3ykUpWlivNE32DLjZEegkMdYR1B8hO"},
	{"Password4","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uDSYGfrlUJ581NlyJCvtpdjpyqImZhie"},
	{"Password5","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uE7XKR0iwQaakusWPVV3LoM9rXR9xmYi"}
};


// some incorrect passwords 
static const struct SPassAndHash  s_incorrectPairs[] = {
	{"Password1inc","$2a$12$kCqMi6/ICcWoNdpqT4Ly7ul5EwEUzZVRZsT0cxUq.cKQGcpGDJ.M."},
	{"Password2inc","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uj7QNDFFHtJyQNyh.DvBYB9mCrlPDJ/u"},
	{"Password3inc","$2a$12$kCqMi6/ICcWoNdpqT4Ly7ui3ykUpWlivNE32DLjZEegkMdYR1B8hO"},
	{"Password4inc","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uDSYGfrlUJ581NlyJCvtpdjpyqImZhie"},
	{"Password5inc","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uE7XKR0iwQaakusWPVV3LoM9rXR9xmYi"}
};



int main(void)
{
	static const size_t scunCorrectsCount = sizeof(s_correctPairs) / sizeof(const struct SPassAndHash);
	static const size_t scunIncorrectsCount = sizeof(s_incorrectPairs) / sizeof(const struct SPassAndHash);
	size_t i;
	bool bComparision;


	for (i = 0; i < scunCorrectsCount; ++i) {
		bComparision = SimpleCppBcryptVerify(s_correctPairs[i].password, s_correctPairs[i].hash);
		assert(bComparision);
	}


	for (i = 0; i < scunCorrectsCount; ++i) {
		bComparision = SimpleCppBcryptVerify(s_incorrectPairs[i].password, s_incorrectPairs[i].hash);
		assert(!bComparision);
	}


	return 0;
}
