//
// file:			0001_check_correct_hashes.cpp
// created on:		2023 Aug 30
//

#include <simple_cpp_bcrypt/bcrypt.h>
#include <cinternal/unit_test.h>
#include <stddef.h>


struct SPassAndHash {
	const char* password;
	const char* hash;
};


// some correct passwords (generated by https://pi7.org/bcrypt-online/)
static const struct SPassAndHash  s_correctPairs[] = {
	{"Password1","$2a$12$kCqMi6/ICcWoNdpqT4Ly7ul5EwEUzZVRZsT0cxUq.cKQGcpGDJ.M."},
	{"Password2","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uj7QNDFFHtJyQNyh.DvBYB9mCrlPDJ/u"},
	{"Password3","$2a$12$kCqMi6/ICcWoNdpqT4Ly7ui3ykUpWlivNE32DLjZEegkMdYR1B8hO"},
	{"Password4","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uDSYGfrlUJ581NlyJCvtpdjpyqImZhie"},
	{"Password5","$2a$12$kCqMi6/ICcWoNdpqT4Ly7uE7XKR0iwQaakusWPVV3LoM9rXR9xmYi"}
};


TEST(f_0001_check_correct_hashes, t_0001)
{
	bool bComparision;
	size_t i;
	const size_t scunCorrectsCount = sizeof(s_correctPairs) / sizeof(const struct SPassAndHash);

	for (i = 0; i < scunCorrectsCount; ++i) {
		bComparision = SimpleCppBcryptVerify(s_correctPairs[i].password, s_correctPairs[i].hash);
		ASSERT_TRUE(bComparision);
	}
}
