#
# file:			check_merge_to_master.yml  
# created on:	2023 Feb 03  
#
# usefull urls:
#				1. https://docs.github.com/en/actions
#				2. https://github.com/actions/starter-workflows
#				3. https://github.com/actions/download-artifact
#

name: check-merge-to-master-and-develop
on:
    pull_request:
        branches: [ master, develop ]

env:
  deployUser: kalantar
  #deployRoot: /home/${{env.deployUser}}/build/3rd-party
  #deployHost: mtcapitzcpu7.ifh.de
  #deployHostAndUser: ${{env.deployUser}}@${{env.deployHost}}


jobs:

    # matrix for unix systems (for now ubuntu-20.04 and ubuntu-22.04, and macos)
    unixes:
        runs-on: ${{ matrix.os }}
        strategy:
          matrix:
            #os: [ubuntu-20.04 ubuntu-22.04]
            include:
              # for all linuxes we should specify lC (lsbCode)
              # lC=$lsbCode=`lsb_release -c | cut -f 2` # for ubuntu18
              #- os: ubuntu-18.04
              #  lC: bionic
              - os: ubuntu-20.04
                lC: focal
              - os: ubuntu-22.04
                lC: jammy
              - os: macos-latest
                lC: mac
              #- os: LinuxMint-19.3
              #  lC: trica
        steps:
            - name: Checking out repository
              uses: actions/checkout@v3
    
            - name: Preparing host for ${{ matrix.os }}
              run: ./scripts/unix_prepare_host.sh
      
            - name: Preparing repository for ${{ matrix.os }}
              run: ./scripts/unix_prepare_repository.sh

            #- name: Install SSH key
            #  uses: shimataro/ssh-key-action@v2
            #  with:
            #   key: ${{ secrets.SSH_KEY }}
            #   #known_hosts: ${{ secrets.KNOWN_HOSTS }}

            - name: Building
              run: ./scripts/unix_build_all.sh

            - name: testing test apps
              run: ./scripts/unix_run_tests.sh


    # This is for windows
    windows:
        runs-on: windows-latest
        steps:
            - name: Checking out repository
              uses: actions/checkout@v3

            - name: Setup MSBuild.exe
              uses: microsoft/setup-msbuild@v1.1

            - name: Setup developer command prompt
              uses: ilammy/msvc-dev-cmd@v1

            - name: Developer host preparation
              run: cmd /C .\scripts\windows_prepare_host.bat
              #working-directory: core

            - name: Repository preparation
              run: cmd /C .\scripts\windows_prepare_repository.bat

            - name: Compiling cinternal all tests
              run: cmd /C .\scripts\windows_build_all.bat

            - name: testing test apps
              run: cmd /C .\scripts\windows_run_tests.bat

    mac:
        #needs: prepare-ubuntu18-host
        runs-on: macos-latest
        steps:
            #- uses: actions/checkout@v2
            - run: >
                echo "Macos tests to be done"